# Generated by Django 2.0.6 on 2018-07-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=2)),
                ('mothertongue', models.CharField(max_length=10)),
                ('englishlevel', models.CharField(max_length=15)),
                ('familiarity', models.IntegerField()),
                ('residence', models.CharField(max_length=3)),
                ('reason', models.CharField(max_length=10)),
            ],
        ),
    ]
