# Generated by Django 2.0.6 on 2018-07-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprgram', '0002_auto_20180719_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('category', models.IntegerField()),
                ('target', models.IntegerField()),
            ],
        ),
    ]
