# Generated by Django 2.0.6 on 2018-07-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprgram', '0003_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='emotionLables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('target', models.IntegerField()),
                ('label', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='intentionLables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('target', models.IntegerField()),
                ('label', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='locationLables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('target', models.IntegerField()),
                ('label', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='relationshipLables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('target', models.IntegerField()),
                ('label', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
