# Generated by Django 2.0.6 on 2018-07-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprgram', '0004_emotionlables_intentionlables_locationlables_relationshiplables'),
    ]

    operations = [
        migrations.CreateModel(
            name='confidenceLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('target', models.IntegerField()),
                ('expressionValue', models.IntegerField()),
                ('contextValue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='similarExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('target', models.IntegerField()),
                ('expr', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='progress',
            name='category',
        ),
    ]
