# Generated by Django 2.0.6 on 2018-07-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprgram', '0005_auto_20180719_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionlables',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='intentionlables',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='locationlables',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='relationshiplables',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
