# Generated by Django 2.0.6 on 2018-07-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprgram', '0005_auto_20180719_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='expressionSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField()),
                ('similar', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='emotionlables',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='intentionlables',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='locationlables',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='relationshiplables',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
