# Generated by Django 2.0.6 on 2018-07-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprgram', '0006_auto_20180729_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionsimilarity',
            name='userid',
            field=models.TextField(default=''),
        ),
    ]
