# Generated by Django 2.0.6 on 2018-07-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exprgram', '0007_expressionsimilarity_userid'),
        ('exprgram', '0006_auto_20180724_0331'),
    ]

    operations = [
    ]
