# Generated by Django 2.0.6 on 2018-08-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exprgram', '0008_merge_20180730_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionlables',
            name='count',
        ),
        migrations.RemoveField(
            model_name='intentionlables',
            name='count',
        ),
        migrations.RemoveField(
            model_name='locationlables',
            name='count',
        ),
        migrations.RemoveField(
            model_name='relationshiplables',
            name='count',
        ),
        migrations.AddField(
            model_name='emotionlables',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expressionsimilarity',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intentionlables',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locationlables',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relationshiplables',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='similarexpression',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
