# Generated by Django 2.0.6 on 2018-08-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exprgram', '0009_auto_20180815_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionlables',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='expressionsimilarity',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='intentionlables',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='locationlables',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='relationshiplables',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='similarexpression',
            name='userid',
        ),
    ]
